In [2]:
%%writefile requirements.txt
numpy
pandas==2.2.3
matplotlib==3.10.0

Overwriting requirements.txt

In [3]:
%pip install -r requirements.txt

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.3.2)
Requirement already satisfied: pandas==2.2.3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: matplotlib==3.10.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gavinsibley/Library/Python/3.12/lib/python/site-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas==2.2.3->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/gavinsibley/Library/Python/3.12/lib/python/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib==3.10.0->-r requirements.txt (line 3)) (3.2.3)
Requirement already satisfied: six>=1.5 in /Users/gavinsibley/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas==2.2.3->-r requirements.txt (line 2)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

First, read in the csv files.

In [5]:
# TODO: Read in credit train and credit test csv
test = pd.read_csv('credit_test.csv')
train = pd.read_csv('credit_train.csv')

In [7]:
# TODO: Return the first 5 rows of the train dataframe\
print(train.head()) # Display the first 5 rows of the DataFrame

                                Loan ID                           Customer ID  \
0  14dd8831-6af5-400b-83ec-68e61888a048  981165ec-3274-42f5-a3b4-d104041a9ca9
1  4771cc26-131a-45db-b5aa-537ea4ba5342  2de017a3-2e01-49cb-a581-08169e83be29
2  4eed4e6a-aa2f-4c91-8651-ce984ee8fb26  5efb2b2b-bf11-4dfd-a572-3761a2694725
3  77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a  e777faab-98ae-45af-9a86-7ce5b33b1011
4  d4062e70-befa-4995-8643-a0de73938182  81536ad9-5ccf-4eb8-befb-47a4d608658e

  Loan Status  Current Loan Amount        Term  Credit Score  Annual Income  \
0  Fully Paid             445412.0  Short Term         709.0      1167493.0
1  Fully Paid             262328.0  Short Term           NaN            NaN
2  Fully Paid           99999999.0  Short Term         741.0      2231892.0
3  Fully Paid             347666.0   Long Term         721.0       806949.0
4  Fully Paid             176220.0  Short Term           NaN            NaN

  Years in current job Home Ownership             Purpose  Monthly Debt  \
0              8 years  Home Mortgage   Home Improvements       5214.74
1            10+ years  Home Mortgage  Debt Consolidation      33295.98
2              8 years       Own Home  Debt Consolidation      29200.53
3              3 years       Own Home  Debt Consolidation       8741.90
4              5 years           Rent  Debt Consolidation      20639.70

   Years of Credit History  Months since last delinquent  \
0                     17.2                           NaN
1                     21.1                           8.0
2                     14.9                          29.0
3                     12.0                           NaN
4                      6.1                           NaN

   Number of Open Accounts  Number of Credit Problems  Current Credit Balance  \
0                      6.0                        1.0                228190.0
1                     35.0                        0.0                229976.0
2                     18.0                        1.0                297996.0
3                      9.0                        0.0                256329.0
4                     15.0                        0.0                253460.0

   Maximum Open Credit  Bankruptcies  Tax Liens
0             416746.0           1.0        0.0
1             850784.0           0.0        0.0
2             750090.0           0.0        0.0
3             386958.0           0.0        0.0
4             427174.0           0.0        0.0

In [8]:
# TODO: Return a summary of the train dataframe
train.info

<bound method DataFrame.info of                                      Loan ID  \
0       14dd8831-6af5-400b-83ec-68e61888a048
1       4771cc26-131a-45db-b5aa-537ea4ba5342
2       4eed4e6a-aa2f-4c91-8651-ce984ee8fb26
3       77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a
4       d4062e70-befa-4995-8643-a0de73938182
...                                      ...
100509                                   NaN
100510                                   NaN
100511                                   NaN
100512                                   NaN
100513                                   NaN

                                 Customer ID Loan Status  Current Loan Amount  \
0       981165ec-3274-42f5-a3b4-d104041a9ca9  Fully Paid             445412.0
1       2de017a3-2e01-49cb-a581-08169e83be29  Fully Paid             262328.0
2       5efb2b2b-bf11-4dfd-a572-3761a2694725  Fully Paid           99999999.0
3       e777faab-98ae-45af-9a86-7ce5b33b1011  Fully Paid             347666.0
4       81536ad9-5ccf-4eb8-befb-47a4d608658e  Fully Paid             176220.0
...                                      ...         ...                  ...
100509                                   NaN         NaN                  NaN
100510                                   NaN         NaN                  NaN
100511                                   NaN         NaN                  NaN
100512                                   NaN         NaN                  NaN
100513                                   NaN         NaN                  NaN

              Term  Credit Score  Annual Income Years in current job  \
0       Short Term         709.0      1167493.0              8 years
1       Short Term           NaN            NaN            10+ years
2       Short Term         741.0      2231892.0              8 years
3        Long Term         721.0       806949.0              3 years
4       Short Term           NaN            NaN              5 years
...            ...           ...            ...                  ...
100509         NaN           NaN            NaN                  NaN
100510         NaN           NaN            NaN                  NaN
100511         NaN           NaN            NaN                  NaN
100512         NaN           NaN            NaN                  NaN
100513         NaN           NaN            NaN                  NaN

       Home Ownership             Purpose  Monthly Debt  \
0       Home Mortgage   Home Improvements       5214.74
1       Home Mortgage  Debt Consolidation      33295.98
2            Own Home  Debt Consolidation      29200.53
3            Own Home  Debt Consolidation       8741.90
4                Rent  Debt Consolidation      20639.70
...               ...                 ...           ...
100509            NaN                 NaN           NaN
100510            NaN                 NaN           NaN
100511            NaN                 NaN           NaN
100512            NaN                 NaN           NaN
100513            NaN                 NaN           NaN

        Years of Credit History  Months since last delinquent  \
0                          17.2                           NaN
1                          21.1                           8.0
2                          14.9                          29.0
3                          12.0                           NaN
4                           6.1                           NaN
...                         ...                           ...
100509                      NaN                           NaN
100510                      NaN                           NaN
100511                      NaN                           NaN
100512                      NaN                           NaN
100513                      NaN                           NaN

        Number of Open Accounts  Number of Credit Problems  \
0                           6.0                        1.0
1                          35.0                        0.0
2                          18.0                        1.0
3                           9.0                        0.0
4                          15.0                        0.0
...                         ...                        ...
100509                      NaN                        NaN
100510                      NaN                        NaN
100511                      NaN                        NaN
100512                      NaN                        NaN
100513                      NaN                        NaN

        Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens
0                     228190.0             416746.0           1.0        0.0
1                     229976.0             850784.0           0.0        0.0
2                     297996.0             750090.0           0.0        0.0
3                     256329.0             386958.0           0.0        0.0
4                     253460.0             427174.0           0.0        0.0
...                        ...                  ...           ...        ...
100509                     NaN                  NaN           NaN        NaN
100510                     NaN                  NaN           NaN        NaN
100511                     NaN                  NaN           NaN        NaN
100512                     NaN                  NaN           NaN        NaN
100513                     NaN                  NaN           NaN        NaN

[100514 rows x 19 columns]>

In [9]:
#Drops duplicates and unnecessary columns
train = train.drop_duplicates()
train = train.drop(columns=['Loan ID', 'Customer ID'], axis=1)

Then, handle all null values.

In [10]:
# TODO: Check for missing values in the train dataframe (Hint: use isnull().sum())
print(train.isnull().sum)

<bound method DataFrame.sum of         Loan Status  Current Loan Amount   Term  Credit Score  Annual Income  \
0             False                False  False         False          False
1             False                False  False          True           True
2             False                False  False         False          False
3             False                False  False         False          False
4             False                False  False          True           True
...             ...                  ...    ...           ...            ...
99996         False                False  False         False          False
99997         False                False  False         False          False
99998         False                False  False         False          False
99999         False                False  False         False          False
100000         True                 True   True          True           True

        Years in current job  Home Ownership  Purpose  Monthly Debt  \
0                      False           False    False         False
1                      False           False    False         False
2                      False           False    False         False
3                      False           False    False         False
4                      False           False    False         False
...                      ...             ...      ...           ...
99996                  False           False    False         False
99997                  False           False    False         False
99998                  False           False    False         False
99999                   True           False    False         False
100000                  True            True     True          True

        Years of Credit History  Months since last delinquent  \
0                         False                          True
1                         False                         False
2                         False                         False
3                         False                          True
4                         False                          True
...                         ...                           ...
99996                     False                         False
99997                     False                         False
99998                     False                          True
99999                     False                          True
100000                     True                          True

        Number of Open Accounts  Number of Credit Problems  \
0                         False                      False
1                         False                      False
2                         False                      False
3                         False                      False
4                         False                      False
...                         ...                        ...
99996                     False                      False
99997                     False                      False
99998                     False                      False
99999                     False                      False
100000                     True                       True

        Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens
0                        False                False         False      False
1                        False                False         False      False
2                        False                False         False      False
3                        False                False         False      False
4                        False                False         False      False
...                        ...                  ...           ...        ...
99996                    False                False         False      False
99997                    False                False         False      False
99998                    False                False         False      False
99999                    False                False         False      False
100000                    True                 True          True       True

[89786 rows x 17 columns]>

In [40]:
# standardize nulls to np.nan, so pandas recognizes them as missing
train.replace(['nan','NaN','NULL','',' '], np.nan, inplace=True)

# TODO: Impute missing values (Hint: Use fillna())
# Hint: you can use median, mode, mean, or a specific value to fill in missing values
train['Current Loan Amount'].fillna(0, inplace=True)
train['Years of Credit History'].fillna(train['Years of Credit History'].median(), inplace=True)

train['Current Loan Amount'].fillna(0, inplace=True)
train['Years of Credit History'].fillna(train['Years of Credit History'].median(), inplace=True)
train['Credit Score'].fillna(train['Credit Score'].median(), inplace=True)
train['Annual Income'].fillna(train['Annual Income'].median(), inplace=True)
train['Monthly Debt'].fillna(train['Monthly Debt'].median(), inplace=True)
train['Number of Open Accounts'].fillna(train['Number of Open Accounts'].median(), inplace=True)
train['Current Credit Balance'].fillna(train['Current Credit Balance'].median(), inplace=True)
train['Maximum Open Credit'].fillna(train['Maximum Open Credit'].median(), inplace=True)
train['Bankruptcies'].fillna(train['Bankruptcies'].median(), inplace=True)
train['Tax Liens'].fillna(train['Tax Liens'].median(), inplace=True)

train['Term'].fillna(train['Term'].mode()[0], inplace=True)
train['Home Ownership'].fillna(train['Home Ownership'].mode()[0], inplace=True)
train['Purpose'].fillna(train['Purpose'].mode()[0], inplace=True)

train['Years in current job'].fillna('Missing', inplace=True)

/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Current Loan Amount'].fillna(0, inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Years of Credit History'].fillna(train['Years of Credit History'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Current Loan Amount'].fillna(0, inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Years of Credit History'].fillna(train['Years of Credit History'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Credit Score'].fillna(train['Credit Score'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Annual Income'].fillna(train['Annual Income'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Monthly Debt'].fillna(train['Monthly Debt'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Number of Open Accounts'].fillna(train['Number of Open Accounts'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Current Credit Balance'].fillna(train['Current Credit Balance'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Maximum Open Credit'].fillna(train['Maximum Open Credit'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Bankruptcies'].fillna(train['Bankruptcies'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Tax Liens'].fillna(train['Tax Liens'].median(), inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Term'].fillna(train['Term'].mode()[0], inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Home Ownership'].fillna(train['Home Ownership'].mode()[0], inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Purpose'].fillna(train['Purpose'].mode()[0], inplace=True)
/var/folders/p3/zhc70_kd6y7fyyttywsfd3vw0000gn/T/ipykernel_43190/2900754829.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Years in current job'].fillna('Missing', inplace=True)

In [41]:
# TODO: Check for missing values again to confirm they were filled
print(train.isnull().sum)

<bound method DataFrame.sum of         Loan Status  Current Loan Amount   Term  Credit Score  Annual Income  \
0             False                False  False         False          False
1             False                False  False         False          False
2             False                False  False         False          False
3             False                False  False         False          False
4             False                False  False         False          False
...             ...                  ...    ...           ...            ...
99996         False                False  False         False          False
99997         False                False  False         False          False
99998         False                False  False         False          False
99999         False                False  False         False          False
100000        False                False  False         False          False

        Years in current job  Home Ownership  Purpose  Monthly Debt  \
0                      False           False    False         False
1                      False           False    False         False
2                      False           False    False         False
3                      False           False    False         False
4                      False           False    False         False
...                      ...             ...      ...           ...
99996                  False           False    False         False
99997                  False           False    False         False
99998                  False           False    False         False
99999                  False           False    False         False
100000                 False           False    False         False

        Years of Credit History  Months since last delinquent  \
0                         False                          True
1                         False                         False
2                         False                         False
3                         False                          True
4                         False                          True
...                         ...                           ...
99996                     False                         False
99997                     False                         False
99998                     False                          True
99999                     False                          True
100000                    False                          True

        Number of Open Accounts  Number of Credit Problems  \
0                         False                      False
1                         False                      False
2                         False                      False
3                         False                      False
4                         False                      False
...                         ...                        ...
99996                     False                      False
99997                     False                      False
99998                     False                      False
99999                     False                      False
100000                    False                       True

        Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens
0                        False                False         False      False
1                        False                False         False      False
2                        False                False         False      False
3                        False                False         False      False
4                        False                False         False      False
...                        ...                  ...           ...        ...
99996                    False                False         False      False
99997                    False                False         False      False
99998                    False                False         False      False
99999                    False                False         False      False
100000                   False                False         False      False

[89786 rows x 17 columns]>

Feature Engineering

In [52]:
# 1a) Years in current job: extract numeric and bin
def extract_years(s):
    s = str(s)
    match = re.findall(r'\d+', s)
    if match:
        return int(match[0])
    return None

train['Years in current job'] = train['Years in current job'].apply(extract_years)

bins = [0, 2, 5, 10, float('inf')]
labels = ['0-2', '2-5', '5-10', '10+']
train['Years in current job'] = pd.cut(train['Years in current job'], bins=bins, labels=labels, right=False)

# ✅ FIXED: Fill NaNs directly without adding duplicate categories
train['Years in current job'] = train['Years in current job'].fillna('0-2')

# 1b) Standardize Purpose values to canonical list
train['Purpose'] = (
    train['Purpose']
        .astype('string')
        .fillna('Missing')
        .replace({
            'Home Improvements':'Home Renovation / Improvement',
            'Debt Consolidation':'Debt Consolidation',
            'Buy House':'Home Purchase / Mortgage',
            'Business Loan':'Business / Startup Capital',
            'Buy a Car':'Car / Vehicle Purchase',
            'Take a Trip':'Vacation / Travel',
            'small_business':'Business / Startup Capital',
            'Medical Bills':'Medical Expenses',
            'wedding':'Wedding Expenses',
            'vacation':'Vacation / Travel',
            'Educational Expenses':'Education / Tuition Fees',
            'moving':'Moving / Relocation Costs',
            'other':'Other / Miscellaneous',
            'Other':'Other / Miscellaneous',
            'renewable_energy':'Buying Electronics / Appliances',
            'major_purchase':'Business / Startup Capital'
        })
)

Then, encode the categorical data.

In [53]:
#Separate categorical and numerical columns
cat_list = train.select_dtypes(include='object').columns.tolist()
num_list = train.select_dtypes(exclude='object').columns.tolist()
print("Categorical:", cat_list)
print("Numerical:", num_list)

Categorical: []
Numerical: ['Loan Status', 'Current Loan Amount', 'Term', 'Credit Score', 'Annual Income', 'Years in current job', 'Home Ownership', 'Purpose', 'Monthly Debt', 'Years of Credit History', 'Months since last delinquent', 'Number of Open Accounts', 'Number of Credit Problems', 'Current Credit Balance', 'Maximum Open Credit', 'Bankruptcies', 'Tax Liens']

In [64]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, OneHotEncoder

# -------------------------
# 2a) Ordinal encode 'Years in current job'
# -------------------------
ordered_labels = ['0-2', '2-5', '5-10', '10+']

# Convert to strings so sklearn doesn't think they're numbers
yrs_col = train['Years in current job'].astype(str).fillna('0-2')

od = OrdinalEncoder(
    categories=[ordered_labels],
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

# sklearn expects a 2D array, so reshape column into (n_rows, 1)
train['Years in current job'] = od.fit_transform(
    yrs_col.to_numpy().reshape(-1, 1)
)

# -------------------------
# 2b) Label encode simple categories
# -------------------------
le = LabelEncoder()
for col in ['Loan Status', 'Term', 'Home Ownership']:
    train[col] = le.fit_transform(train[col].astype(str).fillna('Missing'))

# -------------------------
# 2c) One-hot encode 'Purpose'
# -------------------------
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
purpose_encoded = ohe.fit_transform(train[['Purpose']].astype(str))

purpose_df = pd.DataFrame(
    purpose_encoded,
    columns=ohe.get_feature_names_out(['Purpose']),
    index=train.index
)

train = pd.concat([train.drop('Purpose', axis=1), purpose_df], axis=1)

Finally, create a train/test split.

In [70]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# TODO: Create feature matrix X and target vector y
X = train.drop('Loan Status', axis=1)
y = train['Loan Status']

# TODO: Create a train/test split (Hint: use train_test_split from sklearn)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = 0.2,
    random_state=42,
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [71]:
# Save the processed data to CSV files
import pandas as pd

X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled_df  = pd.DataFrame(X_test_scaled, columns=X_test.columns)

X_train_scaled_df.to_csv("X_train_scaled.csv", index=False)
X_test_scaled_df.to_csv("X_test_scaled.csv", index=False)

y_train.to_csv("y_train.csv", index=False, header=["Loan Status"])
y_test.to_csv("y_test.csv", index=False, header=["Loan Status"])